/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamiflyVsSmarticoRouteImport } from './routes/gamifly-vs-smartico'
import { Route as GamiflyVsFutureAnthemRouteImport } from './routes/gamifly-vs-future-anthem'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources_.$slug'

const GamiflyVsSmarticoRoute = GamiflyVsSmarticoRouteImport.update({
  id: '/gamifly-vs-smartico',
  path: '/gamifly-vs-smartico',
  getParentRoute: () => rootRouteImport,
} as any)
const GamiflyVsFutureAnthemRoute = GamiflyVsFutureAnthemRouteImport.update({
  id: '/gamifly-vs-future-anthem',
  path: '/gamifly-vs-future-anthem',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources_/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/resources_/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/resources/$slug'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/resources/$slug'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/resources_/$slug'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  GamiflyVsFutureAnthemRoute: typeof GamiflyVsFutureAnthemRoute
  GamiflyVsSmarticoRoute: typeof GamiflyVsSmarticoRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gamifly-vs-smartico': {
      id: '/gamifly-vs-smartico'
      path: '/gamifly-vs-smartico'
      fullPath: '/gamifly-vs-smartico'
      preLoaderRoute: typeof GamiflyVsSmarticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamifly-vs-future-anthem': {
      id: '/gamifly-vs-future-anthem'
      path: '/gamifly-vs-future-anthem'
      fullPath: '/gamifly-vs-future-anthem'
      preLoaderRoute: typeof GamiflyVsFutureAnthemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources_/$slug': {
      id: '/resources_/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  GamiflyVsFutureAnthemRoute: GamiflyVsFutureAnthemRoute,
  GamiflyVsSmarticoRoute: GamiflyVsSmarticoRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
