/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsbookGamificationUseCasesRouteImport } from './routes/sportsbook-gamification-use-cases'
import { Route as IgamingGamificationVsCrmBonusCampaignsRouteImport } from './routes/igaming-gamification-vs-crm-bonus-campaigns'
import { Route as GamiflyVsSmarticoRouteImport } from './routes/gamifly-vs-smartico'
import { Route as GamiflyVsFutureAnthemRouteImport } from './routes/gamifly-vs-future-anthem'
import { Route as GamiflyApiIntegrationFlowRouteImport } from './routes/gamifly-api-integration-flow'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CrossProductMissionsInIgamingRouteImport } from './routes/cross-product-missions-in-igaming'
import { Route as CasinoGamificationUseCasesRouteImport } from './routes/casino-gamification-use-cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources_.$slug'

const SportsbookGamificationUseCasesRoute =
  SportsbookGamificationUseCasesRouteImport.update({
    id: '/sportsbook-gamification-use-cases',
    path: '/sportsbook-gamification-use-cases',
    getParentRoute: () => rootRouteImport,
  } as any)
const IgamingGamificationVsCrmBonusCampaignsRoute =
  IgamingGamificationVsCrmBonusCampaignsRouteImport.update({
    id: '/igaming-gamification-vs-crm-bonus-campaigns',
    path: '/igaming-gamification-vs-crm-bonus-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamiflyVsSmarticoRoute = GamiflyVsSmarticoRouteImport.update({
  id: '/gamifly-vs-smartico',
  path: '/gamifly-vs-smartico',
  getParentRoute: () => rootRouteImport,
} as any)
const GamiflyVsFutureAnthemRoute = GamiflyVsFutureAnthemRouteImport.update({
  id: '/gamifly-vs-future-anthem',
  path: '/gamifly-vs-future-anthem',
  getParentRoute: () => rootRouteImport,
} as any)
const GamiflyApiIntegrationFlowRoute =
  GamiflyApiIntegrationFlowRouteImport.update({
    id: '/gamifly-api-integration-flow',
    path: '/gamifly-api-integration-flow',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossProductMissionsInIgamingRoute =
  CrossProductMissionsInIgamingRouteImport.update({
    id: '/cross-product-missions-in-igaming',
    path: '/cross-product-missions-in-igaming',
    getParentRoute: () => rootRouteImport,
  } as any)
const CasinoGamificationUseCasesRoute =
  CasinoGamificationUseCasesRouteImport.update({
    id: '/casino-gamification-use-cases',
    path: '/casino-gamification-use-cases',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources_/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casino-gamification-use-cases': typeof CasinoGamificationUseCasesRoute
  '/cross-product-missions-in-igaming': typeof CrossProductMissionsInIgamingRoute
  '/features': typeof FeaturesRoute
  '/gamifly-api-integration-flow': typeof GamiflyApiIntegrationFlowRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/igaming-gamification-vs-crm-bonus-campaigns': typeof IgamingGamificationVsCrmBonusCampaignsRoute
  '/sportsbook-gamification-use-cases': typeof SportsbookGamificationUseCasesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casino-gamification-use-cases': typeof CasinoGamificationUseCasesRoute
  '/cross-product-missions-in-igaming': typeof CrossProductMissionsInIgamingRoute
  '/features': typeof FeaturesRoute
  '/gamifly-api-integration-flow': typeof GamiflyApiIntegrationFlowRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/igaming-gamification-vs-crm-bonus-campaigns': typeof IgamingGamificationVsCrmBonusCampaignsRoute
  '/sportsbook-gamification-use-cases': typeof SportsbookGamificationUseCasesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casino-gamification-use-cases': typeof CasinoGamificationUseCasesRoute
  '/cross-product-missions-in-igaming': typeof CrossProductMissionsInIgamingRoute
  '/features': typeof FeaturesRoute
  '/gamifly-api-integration-flow': typeof GamiflyApiIntegrationFlowRoute
  '/gamifly-vs-future-anthem': typeof GamiflyVsFutureAnthemRoute
  '/gamifly-vs-smartico': typeof GamiflyVsSmarticoRoute
  '/igaming-gamification-vs-crm-bonus-campaigns': typeof IgamingGamificationVsCrmBonusCampaignsRoute
  '/sportsbook-gamification-use-cases': typeof SportsbookGamificationUseCasesRoute
  '/resources_/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casino-gamification-use-cases'
    | '/cross-product-missions-in-igaming'
    | '/features'
    | '/gamifly-api-integration-flow'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/igaming-gamification-vs-crm-bonus-campaigns'
    | '/sportsbook-gamification-use-cases'
    | '/resources/$slug'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casino-gamification-use-cases'
    | '/cross-product-missions-in-igaming'
    | '/features'
    | '/gamifly-api-integration-flow'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/igaming-gamification-vs-crm-bonus-campaigns'
    | '/sportsbook-gamification-use-cases'
    | '/resources/$slug'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/casino-gamification-use-cases'
    | '/cross-product-missions-in-igaming'
    | '/features'
    | '/gamifly-api-integration-flow'
    | '/gamifly-vs-future-anthem'
    | '/gamifly-vs-smartico'
    | '/igaming-gamification-vs-crm-bonus-campaigns'
    | '/sportsbook-gamification-use-cases'
    | '/resources_/$slug'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasinoGamificationUseCasesRoute: typeof CasinoGamificationUseCasesRoute
  CrossProductMissionsInIgamingRoute: typeof CrossProductMissionsInIgamingRoute
  FeaturesRoute: typeof FeaturesRoute
  GamiflyApiIntegrationFlowRoute: typeof GamiflyApiIntegrationFlowRoute
  GamiflyVsFutureAnthemRoute: typeof GamiflyVsFutureAnthemRoute
  GamiflyVsSmarticoRoute: typeof GamiflyVsSmarticoRoute
  IgamingGamificationVsCrmBonusCampaignsRoute: typeof IgamingGamificationVsCrmBonusCampaignsRoute
  SportsbookGamificationUseCasesRoute: typeof SportsbookGamificationUseCasesRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sportsbook-gamification-use-cases': {
      id: '/sportsbook-gamification-use-cases'
      path: '/sportsbook-gamification-use-cases'
      fullPath: '/sportsbook-gamification-use-cases'
      preLoaderRoute: typeof SportsbookGamificationUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igaming-gamification-vs-crm-bonus-campaigns': {
      id: '/igaming-gamification-vs-crm-bonus-campaigns'
      path: '/igaming-gamification-vs-crm-bonus-campaigns'
      fullPath: '/igaming-gamification-vs-crm-bonus-campaigns'
      preLoaderRoute: typeof IgamingGamificationVsCrmBonusCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamifly-vs-smartico': {
      id: '/gamifly-vs-smartico'
      path: '/gamifly-vs-smartico'
      fullPath: '/gamifly-vs-smartico'
      preLoaderRoute: typeof GamiflyVsSmarticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamifly-vs-future-anthem': {
      id: '/gamifly-vs-future-anthem'
      path: '/gamifly-vs-future-anthem'
      fullPath: '/gamifly-vs-future-anthem'
      preLoaderRoute: typeof GamiflyVsFutureAnthemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamifly-api-integration-flow': {
      id: '/gamifly-api-integration-flow'
      path: '/gamifly-api-integration-flow'
      fullPath: '/gamifly-api-integration-flow'
      preLoaderRoute: typeof GamiflyApiIntegrationFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-product-missions-in-igaming': {
      id: '/cross-product-missions-in-igaming'
      path: '/cross-product-missions-in-igaming'
      fullPath: '/cross-product-missions-in-igaming'
      preLoaderRoute: typeof CrossProductMissionsInIgamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-gamification-use-cases': {
      id: '/casino-gamification-use-cases'
      path: '/casino-gamification-use-cases'
      fullPath: '/casino-gamification-use-cases'
      preLoaderRoute: typeof CasinoGamificationUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources_/$slug': {
      id: '/resources_/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasinoGamificationUseCasesRoute: CasinoGamificationUseCasesRoute,
  CrossProductMissionsInIgamingRoute: CrossProductMissionsInIgamingRoute,
  FeaturesRoute: FeaturesRoute,
  GamiflyApiIntegrationFlowRoute: GamiflyApiIntegrationFlowRoute,
  GamiflyVsFutureAnthemRoute: GamiflyVsFutureAnthemRoute,
  GamiflyVsSmarticoRoute: GamiflyVsSmarticoRoute,
  IgamingGamificationVsCrmBonusCampaignsRoute:
    IgamingGamificationVsCrmBonusCampaignsRoute,
  SportsbookGamificationUseCasesRoute: SportsbookGamificationUseCasesRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
